import type { Metadata } from "next";
import Navbar from "@/components/Navbar/Navbar";

import "./globals.css";
import { Poppins } from "next/font/google";
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col ${poppins.className}`}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
